kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-configmap-products
data:
  database_url: jdbc:mysql://db-mysql-products:3306/dbproducts?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
  database_user: "root"
  database_password: "test1234"
