# https://github.com/thiagohernandes/kubernetes-order
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql-products
  labels:
    app: db-mysql-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-mysql-products
  template:
    metadata:
      labels:
        app: db-mysql-products
    spec:
      containers:
        - name: db-mysql-products
          image: mysql:5.6
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: "dbproducts"
            - name: MYSQL_PASSWORD
              value: "123456"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: db-mysql-pvc-products
